version: "3"

services:
  db:
    image: postgres:latest
    volumes:
      - ./nba-db_export.sql.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
